### ISSUE TITLE
ImportError: cannot import name 'YamlModel' from 'pydantic_yaml'

### ISSUE THREAD

**Issue by AurelienLourot** [canonical/craft-parts#158]
I believe this is because `setup.py` should pin `pydantic-yaml==0.4.2`, as this is also done in `requirements.txt` and `requirements-dev.txt`. Otherwise we are getting pydantic-yaml 0.5.1, for which the way of importing has changed.

```
build run-test: commands[0] | charmcraft build
Traceback (most recent call last):
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/bin/charmcraft", line 5, in <module>
    from charmcraft.main import main
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/charmcraft/main.py", line 26, in <module>
    from charmcraft import config, __version__
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/charmcraft/config.py", line 81, in <module>
    from charmcraft.parts import validate_part
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/charmcraft/parts.py", line 26, in <module>
    from craft_parts import LifecycleManager, Step, plugins
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/__init__.py", line 25, in <module>
    from .lifecycle_manager import LifecycleManager  # noqa: F401
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/lifecycle_manager.py", line 27, in <module>
    from craft_parts import errors, executor, packages, plugins, sequencer
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/executor/__init__.py", line 19, in <module>
    from .executor import ExecutionContext, Executor  # noqa: F401
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/executor/executor.py", line 35, in <module>
    from .part_handler import PartHandler
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/executor/part_handler.py", line 34, in <module>
    from craft_parts.state_manager import MigrationState, StepState, states
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/state_manager/__init__.py", line 19, in <module>
    from .state_manager import StateManager  # noqa: F401
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/state_manager/state_manager.py", line 32, in <module>
    from .states import StepState, get_step_state_path, load_step_state
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/state_manager/states.py", line 29, in <module>
    from .build_state import BuildState
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/state_manager/build_state.py", line 23, in <module>
    from .step_state import StepState, validate_hex_string
  File "/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/craft_parts/state_manager/step_state.py", line 23, in <module>
    from pydantic_yaml import YamlModel  # type: ignore
ImportError: cannot import name 'YamlModel' from 'pydantic_yaml' (/home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/lib/python3.9/site-packages/pydantic_yaml/__init__.py)
ERROR: InvocationError for command /home/lourot/Documents/git/canonical/charm-nova-compute-nvidia-vgpu/.tox/build/bin/charmcraft build (exited with code 1)

```

**Comment by cmatsuoka** [comment]
This should be addressed in PR #159. For some reason `YamlModel` can't be imported in 0.5.1 even if it's exported by the package, so I pinned it as suggested.
