### ISSUE TITLE
Organizing components fails if equivalent file already exists

### ISSUE THREAD

**Issue by dilyn-corner** [canonical/craft-parts#673]
### Bug Description

When a `part` defines an `organize:` which includes moving a file into a (not `default`) component partition, the organize will fail just in case the file already exists in that partition.

This behavior breaks from how that functionality works when not organizing into a component, where the collision of identical files is ignored.

This problem only seems to impact organizing into a partition which isn't `default`. To see this, remove the `organize:` from `my-part` in the below `snapcraft.yaml` and run `snapcraft build my-part --verbose` twice. It should not fail.

I would expect the behavior to match regardless of the name of the partition the file is being organized into.

### To Reproduce

Install snapcraft from a feature branch and create a boilerplate snap:

```
snap switch --channel=latest/edge/components snapcraft; snap refresh snapcraft
# Tested with revision 10677
mkdir test; cd test; snapcraft init
```

Create some simple files:
```
mkdir src/
touch src/default-file src/foo-file
```

Use the below `snapcraft.yaml` and run `snapcraft build my-part --verbose` twice.

To compare the behavior when not organizing into a component not named `default`, remove the `organize` section.
To compare the behavior when not using components, remove the `components:` section and the usage of `organize:`.
Both of these comparisons should succeed, while the provided example fails.

### part yaml

```shell
name: my-snap-name # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
build-base: devel
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    plugin: dump
    source: src/
    organize:
      foo-file: (component/foo)/foo-file

components:
  foo:
    type: test
    summary: test
    description: test
```

### Relevant log output

```shell
dilyn@Ares:~/test -> snapcraft build my-part --verbose
Starting snapcraft                                                                                                                                             
Logging execution to '/home/dilyn/.local/state/snapcraft/log/snapcraft-20240227-175558.077912.log'                                                             
Starting snapcraft                                                                                                                                             
Logging execution to '/home/dilyn/.local/state/snapcraft/log/snapcraft-20240227-175558.077912.log'                                                             
deleting current features configuration                                                                                                                        
Running on amd64 for amd64                                                                                                                                     
Running snapcraft with a devel instance is for testing purposes only.                                                                                          
Launching instance...                                                                                                                                          
Creating instance from base instance                                                                                                                           
Starting instance \ (11.7s)                                                                         Starting instance \ (14.1s)                                 Starting instance                                                                                                                                              
Starting snapcraft                                                                                                                                             
Logging execution to '/root/.local/state/snapcraft/log/snapcraft-20240227-175622.766916.log'                                                                   
Starting snapcraft                                                                                                                                             
Logging execution to '/root/.local/state/snapcraft/log/snapcraft-20240227-175622.766916.log'                                                                   
deleting current features configuration                                                                                                                        
Running on amd64 for amd64                                                                                                                                     
Initializing parts lifecycle                                                                                                                                   
Installing build-packages                                                                                                                                      
Installing build-snaps                                                                                                                                         
Pulling my-part                                                                                                                                                
Building my-part                                                                                                                                               
:: + cp --archive --link --no-dereference . /root/parts/my-part/install/default                                                                                
dilyn@Ares:~/test -> snapcraft build my-part --verbose 
Starting snapcraft                                                                                                                                             
Logging execution to '/home/dilyn/.local/state/snapcraft/log/snapcraft-20240227-175642.418888.log'                                                             
Starting snapcraft                                                                                                                                             
Logging execution to '/home/dilyn/.local/state/snapcraft/log/snapcraft-20240227-175642.418888.log'                                                             
deleting current features configuration                                                                                                                        
Running on amd64 for amd64                                                                                                                                     
Running snapcraft with a devel instance is for testing purposes only.                                                                                          
Launching instance...                                                                                                                                          
Starting instance                                                                                                                                              
Starting snapcraft                                                                                                                                             
Logging execution to '/root/.local/state/snapcraft/log/snapcraft-20240227-175653.254644.log'                                                                   
Starting snapcraft                                                                                                                                             
Logging execution to '/root/.local/state/snapcraft/log/snapcraft-20240227-175653.254644.log'                                                                   
deleting current features configuration                                                                                                                        
Running on amd64 for amd64                                                                                                                                     
Initializing parts lifecycle                                                                                                                                   
Installing build-packages                                                                                                                                      
Installing build-snaps                                                                                                                                         
Skipping pull for my-part (already ran)                                                                                                                        
Rebuilding my-part (requested step)                                                                                                                            
:: + cp --archive --link --no-dereference . /root/parts/my-part/install/default                                                                                
Failed to organize part 'my-part': trying to organize file 'foo-file' to '(component/foo)/foo-file', but '(component/foo)/foo-file' already exists.            
Failed to execute build in instance.                                                                                                                           
Recommended resolution: Run the same command again with --debug to shell into the environment if you wish to introspect this failure.                          
Full execution log: '/home/dilyn/.local/state/snapcraft/log/snapcraft-20240227-175642.418888.log'
```

**Comment by dilyn-corner** [comment]
I've stumbled upon another case which isn't dependent on components:

```
Building grub
:: + craftctl default
:: + cp --archive --link --no-dereference . /root/parts/grub/install
:: cp: cannot create hard link '/root/parts/grub/install/./grub.builtin' to './grub.builtin': File exists
:: cp: cannot create hard link '/root/parts/grub/install/./uEnv.txt' to './uEnv.txt': File exists
:: error:
:: Traceback (most recent call last):
::   File "/snap/snapcraft/current/lib/python3.10/site-packages/craft_parts/ctl.py", line 111, in main
::     ret = CraftCtl.run(cmd, args)
::   File "/snap/snapcraft/current/lib/python3.10/site-packages/craft_parts/ctl.py", line 45, in run
::     _client(cmd, args)
::   File "/snap/snapcraft/current/lib/python3.10/site-packages/craft_parts/ctl.py", line 98, in _client
::     raise RuntimeError(message)
:: RuntimeError: Failed to run the build script for part 'grub'.
'override-build' in part 'grub' failed with code 1.
Review the scriptlet and make sure it's correct.
Launching shell on build environment... 
```

The part in question specifies a directory in the project root as a `source` and does no manipulation of those files.

**Comment by mr-cal** [comment]
Renaming this issue because it can be reproduced without the partitions feature.

```
:: cp: cannot create hard link '/root/parts/grub/install/./grub.builtin' to './grub.builtin': File exists
```

I'm not sure if this is a bug, is there a valid case where you would want to organize a file to and from the same location?

**Comment by dilyn-corner** [comment]
I don't want to do it, but snapcraft really wants to.

If the snap build fails but this organize bit has already run, rerunning the build results in the `cp` error. This means that I have to not only redo the build from the point of failure, but I also have to redo the build for that part entirely.

**Comment by wills721** [comment]
Was this even fixed?

**Comment by mr-cal** [comment]
@wills721, it's still on our backlog but hasn't been fixed yet.

**Comment by wills721** [comment]
That hurts.  I build python 3.11 in my snap but then try to install python3-dev in another part in my snap and I get these errors which stops me in my tracks -- trying all sorts of things to work around it. @mr-cal

**Comment by mr-cal** [comment]
Sorry about that - I'd like to know more about your project, as there may be some alternatives but the [forum](https://forum.snapcraft.io/) would be a better place to discuss and get more visibility.  Thanks.

**Comment by wills721** [comment]
Here is my snapcraft.yaml file.  I am using greengrass (aws) but I need to use Python 3.11 within greengrass.  Greengrass supports custom components and for me these are all in Python but upon installation of some python packages pip will lauccn gcc to compile and this fails.  Normally one would do a sudo apt install python3-dev so all the header files and libraries are there for pip but due to the conflicts I cannot add python3-dev.  I did try to post this first on the forum but no one answered.  You can see some of the things I've tried (but didn't work) by what is commented out

name: aws-iot-greengrass-v2
base: core22
# GGv2 version, such as 2.14.1
version: 2.14.1
summary: AWS supported software that extends cloud capabilities to local devices.
description: |
  AWS supported software that extends cloud capabilities to local devices.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

system-usernames:
  snap_daemon: shared

# declare home plug to allow access to files owned by the user in the user’s home ($HOME) directory
plugs:
  home-for-greengrass:
    interface: home
    read: all
  docker-cli:
    interface: docker
  docker-executables:
    content: docker-executables
    default-provider: docker
    interface: content
    target: $SNAP/docker-env
  root-dot-docker:
    interface: personal-files
    write:
    - $HOME/.docker

parts:
  python:
    plugin: autotools
    source: https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tgz
    autotools-configure-parameters:
      - --enable-optimizations
      - --prefix=/usr
    build-packages:
       - build-essential
       - gdb
       - lcov
       - pkg-config
       - libbz2-dev
       - libffi-dev
       - libgdbm-dev
       - libgdbm-compat-dev
       - liblzma-dev
       - libncurses5-dev
       - libreadline6-dev
       - libsqlite3-dev
       - libssl-dev
       - lzma
       - lzma-dev
       - tk-dev
       - uuid-dev
       - zlib1g-dev
    stage-packages:
       - libfontconfig1
       - libfreetype6
       - libgdbm-compat4
       - libgdbm6
       - libpng16-16
       - libtcl8.6
       - libtk8.6
       - libx11-6
       - libxau6
       - libxcb1
       - libxdmcp6
       - libxext6
       - libxft2
       - libxrender1
       - libxss1
    prime:
      - -etc
      - -lib/systemd
      - -usr/bin/2to3
      - -usr/bin/2to3-3.11
      - -usr/bin/deb-systemd-helper
      - -usr/bin/deb-systemd-invoke
      - -usr/bin/easy_install-3.11
      - -usr/bin/idle3
      - -usr/bin/idle3.11
      - -usr/bin/pydoc3
      - -usr/bin/pydoc3.11
      # - -usr/bin/python3.11-config
      # - -usr/bin/python3-config
      - -usr/bin/uuidgen
      # - -usr/include
      # - -usr/lib/*.a
      # - -usr/lib/pkgconfig
      - -usr/lib/python3.11/test
      # - -usr/sbin
      # - -usr/share
      # - -var

  greengrass:
    # See 'snapcraft plugins'
    after:
      - python
    plugin: dump
    # Add source link, in format https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-2.14.1.zip
    source: https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-2.14.1.zip
    stage-packages:
      - openjdk-11-jre-headless
      - minicom
      - gcc
      - curl
      - tar
      # - python3-dev
      # - python3-venv
      - zlib1g-dev
      - libopenblas-dev
      - libc6-dev
      - libjpeg-dev
      - build-essential
      - lshw
      - libreadline6-dev
      - lsb-release
      - libtiff5-dev
      - libjpeg8-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - libtcl8.6
      - libtk8.6
      - libusb-1.0-0
      - python3-rpi.gpio
    build-packages:
      # We need to replace dangling symlink for java ssl certs.
      - ca-certificates-java
    stage:
      - -bin/python
      - -bin/python3
      - -bin/python3.11
    override-build: |
      # execute default build step

      # craftctl default

      # cp -r /root/stage/usr/lib/python3.10 /root/parts/greengrass/install/usr/lib/python3.10
      # cp -r /root/stage/usr/bin/python3.10 /root/parts/greengrass/install/usr/bin/python3.10
      # cp -r /root/parts/python/install/usr/include/python3.10 /root/parts/greengrass/install/usr/include/python3.10/python3.10
      # cp -r /root/parts/python/install/usr/include/python3.10 /root/parts/greengrass/install/usr/include/python3.10
      # cp -r /root/parts/python/install/usr/include/python3.10 /root/parts/greengrass/install/usr/include/aarch64-linux-gnu/python3.10/python3.10
      # cp -r /root/parts/python/install/usr/include /root/parts/greengrass/install/usr/include
      # cp -r /root/parts/python/install/usr/include /usr/include
      # cp -r /root/parts/python/install/usr/bin /usr/bin
      # cp -r /root/parts/python/install/usr/bin /root/parts/greengrass/install/usr/bin
      # cp -r /root/parts/python/install/usr/bin /root/stage/usr/bin
      # cp -r /root/parts/python/install/usr/bin /root/parts/greengrass/install/usr/bin/bin
      # cp -r /root/parts/python/install/usr/lib/python3.10 /root/parts/greengrass/install/usr/lib
      # cp -r /root/parts/python/install/usr/lib/python3.10/config-3.10-aarch64-linux-gnu /root/parts/greengrass/install/usr/lib/python3.10/config-3.10-aarch64-linux-gnu
      # cp -r /root/parts/python/install/usr/lib/python3.10 /root/parts/greengrass/install/usr/lib/python3.10

      snapcraftctl build


      cd "$SNAPCRAFT_PART_INSTALL/usr/lib/jvm" || exit 2

      # The java-8-openjdk-<arch> dir has a different name for each arch, so
      # we need a symlink that references the actual name.
      # Described in: https://forum.snapcraft.io/t/advanced-grammar-for-layouts-or-workaround/17177/4

      # This will be a symlink to the arch-specific openjdk directory.
      OPENJDK_DIR_SYMLINK="java-11-openjdk-arch-symlink"

      case $(arch) in
              aarch64)
              OPENJDK_DIR="java-11-openjdk-arm64"
              ;;
      esac

      case $(arch) in
              x86_64)
              OPENJDK_DIR="java-11-openjdk-amd64"
              ;;
      esac

      ln -s "$OPENJDK_DIR" "$OPENJDK_DIR_SYMLINK" || \
      (echo "failed to link $OPENJDK_DIR_SYMLINK -> $OPENJDK_DIR" \
      && exit 4)

      # The cacerts under /etc won't be accessible after build-time,
      # so the symlink leading to them will become a dangling symlinnk.
      # To avoid this, we'll copy them to the java subdirectory.
      cp /etc/ssl/certs/java/cacerts \
              "$SNAPCRAFT_PART_INSTALL/usr/lib/jvm/$OPENJDK_DIR_SYMLINK/lib/security/cacerts" \
              || exit 5
      cp /etc/ssl/certs/java/cacerts \
              "$SNAPCRAFT_PART_INSTALL/etc/ssl/certs/java/cacerts" \
              || exit 6

      # python3 -m pip install pillow
      # python3 -m pip install RPi.GPIO
      # (mkdir /home/ggc_user)
      # (cd /home/ggc_user/;curl -O https://www.python.org/ftp/python/3.10.0/Python-3.10.0rc2.tar.xz)
      # cd /home/ggc_user/;tar -xvf /home/ggc_user/Python-3.10.0rc2.tar.xz -C /home/ggc_user)
      # (cp -r /snap/aws-iot-greengrass-v2/x1/usr/lib/aarch64-linux-gnu /home/ggc_user/lib)
      # export CPATH="/var/lib/snapd/hostfs/snap/aws-iot-greengrass-v2/x1/usr/include:/var/lib/snapd/hostfs/snap/aws-iot-greengrass-v2/x1/usr/include/aarch64-linux-gnu:/home/ggc_user/Python-3.10.0rc2/Include:/home/ggc_user/Python-3.10.0rc2/PC:/home/ggc_user/Python-3.10.0rc2/Modules/_decimal/libmpdec"
      # export CFLAGS="-DCONFIG_64 -L/snap/aws-iot-greengrass-v2/x1"
      # export LD_LIBRARY_PATH="/home/ggc_user/lib"
      # python3 -m pip install RPi.GPIO 
      # export CRYPTOGRAPHY_DONT_BUILD_RUST=1
      # craftctl default
      # rm $CRAFT_PART_INSTALL/lib/python3.10/site-packages/greengrass/configuration-default.py
  wrapper-scripts:
    plugin: dump
    source: local-scripts/

layout:
  # symlink java
  /usr/bin/java:
    symlink: $SNAP/usr/lib/jvm/java-11-openjdk-arch-symlink/bin/java

apps:
  greengrass:
    command: exec-loader.sh
    daemon: simple
    install-mode: disable
    plugs:
      - mount-observe
      - network-bind
      - process-control
      - raw-usb
      - hardware-observe
      - log-observe
      - home-for-greengrass
      - docker-cli
      - docker-executables
      - root-dot-docker
      - serial-port
      - physical-memory-control
      - i2c
      - gpio-control

**Comment by cmatsuoka** [comment]
Likely fixed in commit c349e740 (PR #68

     Fixes an issue discovered via canonical/snapcraft#4654 where organize_files() would
     organize in the cwd instead of the project's base_dir.
     ... organize_files now accepts the part's install directories instead of redefining
     them.

Please reopen if this problem still happens.
